pre-commit:
  parallel: true
  commands:
    fmt:
      glob: "*.rs"
      run: cargo fmt --all
      stage_fixed: true

    clippy:
      glob: "*.rs"
      run: cargo clippy --all --all-features -- -D warnings

output:
  - summary
  - failure
