mod auth;
mod fxa_webhooks;
pub mod healthz;
mod multiple_collections;
mod newsletter;
mod notification_processing;
mod notifications;
mod ping;
mod root;
mod search;
mod setttings;
pub mod updates;
pub mod watched_items;
mod whoami;
