mod ai_explain;
mod ai_help;
mod ai_help_history;
mod auth;
mod experiments;
mod fxa_webhooks;
pub mod healthz;
mod multiple_collections;
mod newsletter;
mod ping;
mod play;
mod root;
mod search;
mod settings;
pub mod updates;
mod whoami;
