name: "PR Needs Rebase"

on:
  push:
  pull_request_target:
    branches:
      - main
    types: [synchronize]

permissions:
  # Label pull requests.
  pull-requests: write

jobs:
  label-rebase-needed:
    uses: mdn/workflows/.github/workflows/pr-rebase-needed.yml@main
    with:
      target-repo: "mdn/rumba"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
