on:
  push:
    branches:
      - main

permissions:
  contents: read

name: release-please

jobs:
  release-please:
    if: github.repository == 'mdn/rumba'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
