name: Stage deploy

on:
  push:
    branches:
      - main
      - 634-deploy-workflows

  workflow_call:
    secrets:
      GCP_PROJECT_NAME:
        required: true
      WIP_PROJECT_ID:
        required: true

  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to deploy (default: main)"
        required: false
        default: refs/heads/main

permissions:
  # Read/write GHA cache.
  actions: write
  # Checkout.
  contents: read
  # Authenticate with GCP.
  id-token: write

jobs:
  deploy:
    if: github.repository_owner == 'mdn' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: staging
      ref: ${{ inputs.ref }}
