name: Test

on:
  push:
    branches:
      - main
  pull_request:

# No GITHUB_TOKEN permissions, because we don't use it.
permissions: {}

env:
  MDN_SETTINGS: .settings.test.toml

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: rumba
          POSTGRES_PASSWORD: rumba
          POSTGRES_DB: mdn
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1a3a6d54512beeaffd394f8d516ca16f2c506a20 # v1.97
        with:
          components: rustfmt, clippy
      - name: Cache Cargo registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Run sccache-cache
        uses: Mozilla-Actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - name: FMT
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings
      - name: Build
        run: cargo build --release --all --all-features
      - name: Run tests
        run: RUST_BACKTRACE=1 RUST_LOG=rumba:info MDN_SETTINGS=.settings.test.toml cargo test --all -- --test-threads=1 --nocapture
